apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domainturva-server
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: image=ghcr.io/atk-works/domainturva-core/server:main
    argocd-image-updater.argoproj.io/image.update-strategy: digest
    argocd-image-updater.argoproj.io/image.kustomize.image-name: server
    argocd-image-updater.argoproj.io/image.pull-secret: pullsecret:argocd/ghcr-login
spec:
  project: domainturva
  source:
    repoURL: https://github.com/atk-works/domainturva-core
    targetRevision: main
    path: kubernetes/server
  destination:
    server: https://kubernetes.default.svc
    namespace: domainturva
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
